In [1]:
import tensorflow as tf

2025-12-01 23:21:00.002740: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-12-01 23:21:00.010110: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-12-01 23:21:00.304423: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-12-01 23:21:02.325154: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To tur

In [2]:
import pandas as pd 
import numpy as np 

In [3]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Conv1D
from keras.layers import MaxPooling1D
from tensorflow.keras.optimizers import Adam


In [4]:
data = pd.read_csv("data_should_light.csv")
data = data.iloc[:,1:] 
y = data.iloc[:,-1] 
data = data.iloc[:,0:-1] 

In [5]:
import sklearn 
from sklearn.preprocessing import StandardScaler 
from sklearn.model_selection import train_test_split 


In [6]:
X,X_test,y,y_test = train_test_split(data.to_numpy(),y.to_numpy(),shuffle=True,train_size=0.8)

In [7]:
print(X_test)

[[29.1 51.2  0.8  0.6]
 [27.5 61.4  0.5  0.3]
 [27.8 40.9  0.4  0.7]
 [28.8 83.4  0.7  0.3]
 [23.8 70.4  0.1  0.6]
 [26.9 48.2  0.3  0.4]
 [22.9 43.8  0.8  0.7]
 [26.2 69.1  0.2  1. ]
 [28.8 48.4  0.6  0.5]
 [24.8 53.6  0.9  0.8]
 [33.8 86.8  0.3  0.3]
 [24.8 61.3  0.   0.2]
 [32.2 60.4  0.8  0.7]
 [27.1 52.2  0.8  0.4]
 [28.8 84.   0.4  0.9]
 [30.6 88.4  0.2  0.8]
 [21.3 76.8  0.   0.6]
 [31.9 50.6  0.1  0.6]
 [32.1 54.7  0.1  0. ]
 [21.1 72.9  0.4  0.8]
 [28.5 54.9  0.1  0.9]
 [20.5 63.4  0.5  0. ]
 [25.1 44.5  0.9  0.8]
 [27.1 87.8  0.5  0.7]
 [24.7 49.1  0.3  0.6]
 [29.2 44.   0.1  0.2]
 [24.6 85.7  0.4  0.4]
 [33.4 78.2  1.   0.7]
 [21.8 87.6  0.6  0.6]
 [23.  53.5  0.9  1. ]
 [21.9 88.5  0.8  0.7]
 [33.1 68.9  0.3  0.5]
 [33.4 48.9  0.5  0.7]
 [20.3 76.2  0.9  0.4]
 [29.2 83.9  0.5  0.8]
 [20.5 87.1  0.1  0.5]
 [30.  40.3  0.   0.6]
 [20.9 86.7  0.1  0.4]
 [30.8 70.4  0.4  0.8]
 [24.2 74.8  0.3  0. ]
 [26.2 40.9  0.7  0.1]
 [25.2 49.8  1.   0.2]
 [28.4 76.3  0.8  0.5]
 [29.  50.3

In [8]:
model = Sequential([
    Dense(64, activation='relu'),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')
])


model.compile(optimizer="adam",
              loss='BinaryCrossentropy',
              metrics=['accuracy','mse'])

2025-12-01 23:21:04.000838: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [9]:
model.fit(X, y, epochs=1000, verbose=1) 

Epoch 1/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7203 - loss: 0.7244 - mse: 0.2095   
Epoch 2/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8516 - loss: 0.3666 - mse: 0.1082 
Epoch 3/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8766 - loss: 0.3185 - mse: 0.0930 
Epoch 4/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8750 - loss: 0.3342 - mse: 0.0961 
Epoch 5/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8766 - loss: 0.3103 - mse: 0.0905 
Epoch 6/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8938 - loss: 0.3026 - mse: 0.0873 
Epoch 7/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8781 - loss: 0.3294 - mse: 0.0931 
Epoch 8/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8734 - loss: 0.3238 - mse: 0.0945 
Epoch 9/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8859 - loss: 0.3012 - mse: 0.0871 
Epoch 10/1000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8781 - loss: 0.3675 - 

In [10]:
a = model.predict(X_test)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step 


In [11]:
import tensorflow as tf
a = tf.convert_to_tensor(a, dtype=tf.float32)
y_test = tf.convert_to_tensor(y_test, dtype=tf.float32)

# If `a` are probabilities, threshold them at 0.2
preds = tf.cast(a > 0.2, tf.float32)

# Accuracy
accuracy = tf.keras.metrics.BinaryAccuracy()
accuracy.update_state(y_test, preds)
acc_result = accuracy.result().numpy()

# MSE
mse = tf.keras.metrics.MeanSquaredError()
mse.update_state(y_test, a)
mse_result = mse.result().numpy()

print("Accuracy:", acc_result)
print("MSE:", mse_result)

Accuracy: 0.9375
MSE: 0.041726906


In [12]:
hehe = np.array([[32,72,0.2,0.5]])
y_hat = model.predict(hehe)
print(y_hat)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step
[[0.00255724]]


In [13]:
y_hat = model.predict(hehe)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step


In [14]:
print(y_hat)

[[0.00255724]]


In [15]:
from sklearn.metrics import mean_squared_error

In [16]:
import os
print(os.getcwd())  # See where Python is looking
print(os.path.exists('water_model1.h5'))

/home/harley/Documents/HK251/IOT/BTL/IOT_Project
False


In [17]:
model.export('water1_model')  # Exports to a directory 'water_model' for TFLite/TFServing

# Convert to TensorFlow Lite
converter = tf.lite.TFLiteConverter.from_saved_model('water1_model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]  # Optional: Apply optimizations
tflite_model = converter.convert()

# Save the TFLite model
with open('water_model.tflite', 'wb') as f:
    f.write(tflite_model)

INFO:tensorflow:Assets written to: water1_model/assets


INFO:tensorflow:Assets written to: water1_model/assets


Saved artifact at 'water1_model'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 4), dtype=tf.float32, name='keras_tensor')
Output Type:
  TensorSpec(shape=(None, 1), dtype=tf.float32, name=None)
Captures:
  134297058091504: TensorSpec(shape=(), dtype=tf.resource, name=None)
  134297058413024: TensorSpec(shape=(), dtype=tf.resource, name=None)
  134297793106640: TensorSpec(shape=(), dtype=tf.resource, name=None)
  134297058421648: TensorSpec(shape=(), dtype=tf.resource, name=None)
  134297058421824: TensorSpec(shape=(), dtype=tf.resource, name=None)
  134297056709088: TensorSpec(shape=(), dtype=tf.resource, name=None)
  134297058422000: TensorSpec(shape=(), dtype=tf.resource, name=None)
  134297056716304: TensorSpec(shape=(), dtype=tf.resource, name=None)


W0000 00:00:1764606139.102780  151471 tf_tfl_flatbuffer_helpers.cc:364] Ignored output_format.
W0000 00:00:1764606139.102801  151471 tf_tfl_flatbuffer_helpers.cc:367] Ignored drop_control_dependency.
2025-12-01 23:22:19.103116: I tensorflow/cc/saved_model/reader.cc:83] Reading SavedModel from: water1_model
2025-12-01 23:22:19.103688: I tensorflow/cc/saved_model/reader.cc:52] Reading meta graph with tags { serve }
2025-12-01 23:22:19.103696: I tensorflow/cc/saved_model/reader.cc:147] Reading SavedModel debug info (if present) from: water1_model
I0000 00:00:1764606139.107013  151471 mlir_graph_optimization_pass.cc:437] MLIR V1 optimization pass is not enabled
2025-12-01 23:22:19.107965: I tensorflow/cc/saved_model/loader.cc:236] Restoring SavedModel bundle.
2025-12-01 23:22:19.135756: I tensorflow/cc/saved_model/loader.cc:220] Running initialization op on SavedModel bundle at path: water1_model
2025-12-01 23:22:19.143743: I tensorflow/cc/saved_model/loader.cc:471] SavedModel load for tag

In [18]:
!xxd -i water_model.tflite > water_model.h