In [37]:
import tensorflow as tf

In [38]:
import pandas as pd 
import numpy as np 

In [39]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Conv1D
from keras.layers import MaxPooling1D
from tensorflow.keras.optimizers import Adam


In [40]:
data = pd.read_csv("data_should_light.csv")
data = data.iloc[:,1:] 
y = data.iloc[:,-1] 
data = data.iloc[:,0:-1] 

In [41]:
import sklearn 
from sklearn.preprocessing import StandardScaler 
from sklearn.model_selection import train_test_split 


In [42]:
X,X_test,y,y_test = train_test_split(data.to_numpy(),y.to_numpy(),shuffle=True,train_size=0.8)

In [43]:
print(X_test)

[[2.70e+01 8.87e+01 6.00e-01 5.20e-01]
 [2.70e+01 7.53e+01 9.00e-01 3.70e-01]
 [3.35e+01 5.14e+01 5.40e-01 7.90e-01]
 [1.89e+01 6.70e+01 6.00e-02 5.20e-01]
 [2.96e+01 8.26e+01 7.50e-01 2.10e-01]
 [3.25e+01 8.95e+01 9.40e-01 1.40e-01]
 [3.21e+01 6.80e+01 9.20e-01 6.40e-01]
 [2.24e+01 4.41e+01 8.20e-01 4.50e-01]
 [1.98e+01 4.16e+01 6.20e-01 5.90e-01]
 [1.83e+01 8.58e+01 9.80e-01 1.70e-01]
 [2.20e+01 9.50e+01 8.30e-01 7.20e-01]
 [2.15e+01 5.55e+01 1.00e-02 6.20e-01]
 [3.17e+01 3.67e+01 5.00e-02 4.20e-01]
 [3.12e+01 4.59e+01 1.00e-01 9.90e-01]
 [2.54e+01 8.48e+01 9.00e-02 6.50e-01]
 [2.97e+01 8.34e+01 9.20e-01 4.50e-01]
 [3.30e+01 7.04e+01 3.60e-01 1.30e-01]
 [3.20e+01 3.75e+01 4.50e-01 7.10e-01]
 [2.37e+01 9.32e+01 8.90e-01 8.70e-01]
 [2.73e+01 4.92e+01 4.20e-01 6.60e-01]
 [3.43e+01 7.61e+01 4.20e-01 7.10e-01]
 [3.33e+01 7.02e+01 9.40e-01 8.70e-01]
 [3.16e+01 8.44e+01 3.40e-01 8.00e-01]
 [2.69e+01 9.42e+01 6.60e-01 7.80e-01]
 [2.71e+01 4.20e+01 7.10e-01 9.50e-01]
 [2.65e+01 6.13e+01 4.80e

In [44]:
# Smaller model for embedded systems - reduced from [64,128,64] to [16,16]


model = Sequential(
    [
    Dense(8, activation='relu', input_shape=(4,)),  # 4 features
    Dense(16, activation='relu'),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
    ]
)

model.compile(optimizer="adam",
              loss='BinaryCrossentropy',
              metrics=['accuracy','mse'])

/home/harley/Documents/HK251/IOT/BTL/IOT_Project/myenv/lib/python3.10/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [45]:
model.fit(X, y, epochs=200, verbose=1)  # More epochs since smaller model

Epoch 1/200


10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.4719 - loss: 1.6341 - mse: 0.4325  
Epoch 2/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.4719 - loss: 1.6341 - mse: 0.4325  
Epoch 2/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5219 - loss: 0.9309 - mse: 0.3305 
Epoch 3/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5219 - loss: 0.9309 - mse: 0.3305 
Epoch 3/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5063 - loss: 0.7959 - mse: 0.2929 
Epoch 4/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5063 - loss: 0.7959 - mse: 0.2929 
Epoch 4/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5219 - loss: 0.6816 - mse: 0.2447 
Epoch 5/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5219 - loss: 0.6816 - mse: 0.2447 
Epoch 5/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5875 - loss: 0.6548 - mse: 0.2323 
Epoch 6/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5875 - loss: 0.6548 - mse: 0.2323 
Epoch 6/20

In [46]:
a = model.predict(X_test)

1/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/stepWARNING:tensorflow:5 out of the last 13 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7867bd65d7e0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step


In [47]:
import tensorflow as tf
a = tf.convert_to_tensor(a, dtype=tf.float32)
y_test = tf.convert_to_tensor(y_test, dtype=tf.float32)

# If `a` are probabilities, threshold them at 0.5
preds = tf.cast(a > 0.5, tf.float32)

# Accuracy
accuracy = tf.keras.metrics.BinaryAccuracy()
accuracy.update_state(y_test, preds)
acc_result = accuracy.result().numpy()

# MSE
mse = tf.keras.metrics.MeanSquaredError()
mse.update_state(y_test, a)
mse_result = mse.result().numpy()

print("Accuracy:", acc_result)
print("MSE:", mse_result)

Accuracy: 0.85
MSE: 0.14514425


In [54]:
hehe = np.array([[20,53.0,0.3,0.18]])
y_hat = model.predict(hehe)
print(y_hat)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[[0.8162974]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[[0.8162974]]


In [49]:
y_hat = model.predict(hehe)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step


In [50]:
print(y_hat)

[[0.8162974]]


In [51]:
from sklearn.metrics import mean_squared_error

In [52]:


model.export('water_model')  # Exports to a directory 'water_model' for TFLite/TFServing

# Convert to TensorFlow Lite
converter = tf.lite.TFLiteConverter.from_saved_model('water_model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]  # Optional: Apply optimizations
tflite_model = converter.convert()

# Save the TFLite model
with open('water_model.tflite', 'wb') as f:
    f.write(tflite_model)



INFO:tensorflow:Assets written to: water_model/assets


INFO:tensorflow:Assets written to: water_model/assets


Saved artifact at 'water_model'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 4), dtype=tf.float32, name='keras_tensor_10')
Output Type:
  TensorSpec(shape=(None, 1), dtype=tf.float32, name=None)
Captures:
  132386963818976: TensorSpec(shape=(), dtype=tf.resource, name=None)
  132386955440224: TensorSpec(shape=(), dtype=tf.resource, name=None)
  132386955441808: TensorSpec(shape=(), dtype=tf.resource, name=None)
  132386955437936: TensorSpec(shape=(), dtype=tf.resource, name=None)
  132386955440752: TensorSpec(shape=(), dtype=tf.resource, name=None)
  132386956218560: TensorSpec(shape=(), dtype=tf.resource, name=None)
  132386956214688: TensorSpec(shape=(), dtype=tf.resource, name=None)
  132386956216448: TensorSpec(shape=(), dtype=tf.resource, name=None)


W0000 00:00:1764755980.561895  119435 tf_tfl_flatbuffer_helpers.cc:364] Ignored output_format.
W0000 00:00:1764755980.561918  119435 tf_tfl_flatbuffer_helpers.cc:367] Ignored drop_control_dependency.
2025-12-03 16:59:40.562091: I tensorflow/cc/saved_model/reader.cc:83] Reading SavedModel from: water_model
2025-12-03 16:59:40.562746: I tensorflow/cc/saved_model/reader.cc:52] Reading meta graph with tags { serve }
2025-12-03 16:59:40.562752: I tensorflow/cc/saved_model/reader.cc:147] Reading SavedModel debug info (if present) from: water_model
2025-12-03 16:59:40.566423: I tensorflow/cc/saved_model/loader.cc:236] Restoring SavedModel bundle.
2025-12-03 16:59:40.593090: I tensorflow/cc/saved_model/loader.cc:220] Running initialization op on SavedModel bundle at path: water_model
2025-12-03 16:59:40.600449: I tensorflow/cc/saved_model/loader.cc:471] SavedModel load for tags { serve }; Status: success: OK. Took 38359 microseconds.


In [53]:
!xxd -i water_model.tflite > water_model.h