In [3]:
import tensorflow as tf

2025-11-11 16:24:51.880027: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-11-11 16:24:51.891515: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-11-11 16:24:52.062968: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-11-11 16:24:56.144413: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To tur

In [4]:
import pandas as pd 
import numpy as np 

In [5]:
from tensorflow import keras 

In [6]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Conv1D
from keras.layers import MaxPooling1D
from tensorflow.keras.optimizers import Adam


In [7]:
data = pd.read_csv("data_should_light.csv")
y = data.iloc[:,-2] 
data = data.iloc[:,0:-2] 

In [8]:
import sklearn 
from sklearn.preprocessing import StandardScaler 
from sklearn.model_selection import train_test_split 


In [9]:
X,X_test,y,y_test = train_test_split(data.to_numpy(),y.to_numpy(),shuffle=True,train_size=0.2)

In [10]:
print(X_test)

[[1.49e+02 2.08e+01 8.37e+01 8.00e-01]
 [2.45e+02 2.02e+01 8.43e+01 9.00e-01]
 [4.14e+02 2.86e+01 7.97e+01 1.00e-01]
 ...
 [1.03e+02 2.47e+01 4.91e+01 3.00e-01]
 [1.14e+02 3.21e+01 6.05e+01 5.00e-01]
 [1.23e+02 2.48e+01 8.47e+01 3.00e-01]]


In [11]:
model = Sequential(
    [
    Dense(8, activation='relu', input_shape=(4,)),  # 4 features
    Dense(16, activation='relu'),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
    ]
)

model.compile(optimizer="adam",
              loss='BinaryCrossentropy',
              metrics=['accuracy','mse'])

/home/harley/Documents/HK251/IOT/BTL/IOT_Project/myenv/lib/python3.10/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2025-11-11 16:25:00.388651: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [12]:
model.fit(X, y, epochs=1000, verbose=1) 

Epoch 1/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - accuracy: 0.0500 - loss: 4.1932 - mse: 0.2982
Epoch 2/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.0375 - loss: 2.9201 - mse: 0.3049    
Epoch 3/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.0750 - loss: 1.9384 - mse: 0.2575
Epoch 4/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.0500 - loss: 1.9027 - mse: 0.2531
Epoch 5/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.0625 - loss: 1.5375 - mse: 0.2345
Epoch 6/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.0562 - loss: 1.3157 - mse: 0.2238
Epoch 7/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.0562 - loss: 1.1260 - mse: 0.1978
Epoch 8/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.0625 - loss: 0.9592 - mse: 0.1675
Epoch 9/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.0562 - loss: 0.8694 - mse: 0.1418
Epoch 10/1000
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.0688 - loss: 0.8132 - mse: 0.1271
Epoch

In [13]:
a = model.predict(X_test)

20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step


In [14]:
import tensorflow as tf
a = tf.convert_to_tensor(a, dtype=tf.float32)
y_test = tf.convert_to_tensor(y_test, dtype=tf.float32)

# If `a` are probabilities, threshold them at 0.5
preds = tf.cast(a > 0.8, tf.float32)

# Accuracy
accuracy = tf.keras.metrics.BinaryAccuracy()
accuracy.update_state(y_test, preds)
acc_result = accuracy.result().numpy()

# MSE
mse = tf.keras.metrics.MeanSquaredError()
mse.update_state(y_test, a)
mse_result = mse.result().numpy()

print("Accuracy:", acc_result)
print("MSE:", mse_result)

Accuracy: 0.0546875
MSE: 0.11107685


In [15]:
hehe = np.array([[32,72,0.2,0.5]])
y_hat = model.predict(hehe)
print(y_hat)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step
[[0.15802363]]


In [16]:
y_hat = model.predict(hehe)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step


In [17]:
print(y_hat)

[[0.15802363]]


In [18]:
from sklearn.metrics import mean_squared_error

In [19]:
import os
print(os.getcwd())  # See where Python is looking
print(os.path.exists('water_model1.h5'))

/home/harley/Documents/HK251/IOT/BTL/IOT_Project
False


In [20]:
model.export('water1_model')  # Exports to a directory 'water_model' for TFLite/TFServing

# Convert to TensorFlow Lite
converter = tf.lite.TFLiteConverter.from_saved_model('water1_model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]  # Optional: Apply optimizations
tflite_model = converter.convert()

# Save the TFLite model
with open('water_model.tflite', 'wb') as f:
    f.write(tflite_model)

INFO:tensorflow:Assets written to: water1_model/assets


INFO:tensorflow:Assets written to: water1_model/assets


Saved artifact at 'water1_model'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 4), dtype=tf.float32, name='keras_tensor')
Output Type:
  TensorSpec(shape=(None, 1), dtype=tf.float32, name=None)
Captures:
  129034271505072: TensorSpec(shape=(), dtype=tf.resource, name=None)
  129034271502432: TensorSpec(shape=(), dtype=tf.resource, name=None)
  129034271502784: TensorSpec(shape=(), dtype=tf.resource, name=None)
  129034267775344: TensorSpec(shape=(), dtype=tf.resource, name=None)
  129034267774464: TensorSpec(shape=(), dtype=tf.resource, name=None)
  129034267771824: TensorSpec(shape=(), dtype=tf.resource, name=None)
  129034267773232: TensorSpec(shape=(), dtype=tf.resource, name=None)
  129034267774288: TensorSpec(shape=(), dtype=tf.resource, name=None)


W0000 00:00:1762853236.135475   10908 tf_tfl_flatbuffer_helpers.cc:364] Ignored output_format.
W0000 00:00:1762853236.135521   10908 tf_tfl_flatbuffer_helpers.cc:367] Ignored drop_control_dependency.
2025-11-11 16:27:16.136520: I tensorflow/cc/saved_model/reader.cc:83] Reading SavedModel from: water1_model
2025-11-11 16:27:16.138683: I tensorflow/cc/saved_model/reader.cc:52] Reading meta graph with tags { serve }
2025-11-11 16:27:16.138713: I tensorflow/cc/saved_model/reader.cc:147] Reading SavedModel debug info (if present) from: water1_model
I0000 00:00:1762853236.149539   10908 mlir_graph_optimization_pass.cc:437] MLIR V1 optimization pass is not enabled
2025-11-11 16:27:16.152330: I tensorflow/cc/saved_model/loader.cc:236] Restoring SavedModel bundle.
2025-11-11 16:27:16.228075: I tensorflow/cc/saved_model/loader.cc:220] Running initialization op on SavedModel bundle at path: water1_model
2025-11-11 16:27:16.247523: I tensorflow/cc/saved_model/loader.cc:471] SavedModel load for tag

In [23]:
!xxd -i water_model.tflite > water_model.h